### ISSUE TITLE
Tags not being pushed to remote on prerelease version

### ISSUE THREAD

**Issue by mph006** [Netflix/unleash#3]
Check out recent work on abacus-editor/abacus

**Comment by jameswomack** [comment]
Thank you @mph006 I'll look into this

**Comment by hekike** [comment]
I belive it's not just a prerelease issue, unleash should push the specific tag to origin after it's created, if I interpret the current flow correctly it's created on local only, so will be pushed only with the next release.

Pushing specific tag only: `git push origin refs/tags/tag_a` 

@mph006 what do you think?

**Comment by jameswomack** [comment]
It is a bug in the Gulp Plugin being used. I’ve a fix I’m publishing soon.
