### ISSUE TITLE
Only git release 

### ISSUE THREAD

**Issue by rahil471** [Netflix/unleash#5]
Is there a way to configure `unleash` to only do Git or npm? 

I have a node service where I would like to have releases on git but I do not want to publish it as an npm package.

**Comment by jameswomack** [comment]
@rahil471 Not currently, but I'm happy to enable this

**Comment by jameswomack** [comment]
@rahil471 @Falieson I'm working on a branch of Unleash that contains support for git/push-only or npm/publish-only unleashes. I'll update this issue when that's complete.

**Comment by goodmind** [comment]
Any progress here?

**Comment by jameswomack** [comment]
Yes sir! I use it on my projects already and I’m publishing this feature in the next few days.

**Comment by jameswomack** [comment]
@goodmind @Falieson @rahil471 Both publish-only & push-only deployments/releases are possible in the latest Unleash release

**Comment by rahil471** [comment]
Thanks for your efforts @jameswomack .

**Comment by jameswomack** [comment]
You’re most welcome @rahil471
